### ISSUE TITLE
Create a spring boot application for backend development.

### ISSUE THREAD

**Issue by Afroprogrammer** [Turntabl-Exe/Turntabl_Recruitment_Tracker#2]
-- Use Gradle dependencies
-- Springboot dependencies must include

- [x] Spring Web

- [x] Spring JPA
- [x] Postgress SQL
❗ project name would com.turntabl-exe

for steps on how to create a spring boot application, you can visit 
[Here](https://spring.io/guides/gs/spring-boot/)

- [x] Push the files to the backend folder in the repository

@Yaa-Providence-Design

**Comment by Yaa-Providence-Design** [comment]
I added web services since we'll be needing that
